@TodoApi_HostAddress = https://localhost:7019

GET {{TodoApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{TodoApi_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "Estudar API",
  "isComplete": false
}

###
 

###
# Atualizar um item
PUT {{TodoApi_HostAddress}}/api/todoitems/1
Content-Type: application/json

{
  "id": 1,
  "name": "Estudar API - atualizado",
  "isComplete": true
}

###
# Deletar um item
DELETE {{TodoApi_HostAddress}}/api/todoitems/1
